// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class LogLevel(val raw: Int) {
  VERBOSE(0),
  DEBUG(1),
  INFO(2),
  WARN(3),
  ERROR(4),
  OFF(5);

  companion object {
    fun ofRaw(raw: Int): LogLevel? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TokenResp (
  val token: String? = null,
  /** see https://dev.vivo.com.cn/documentCenter/doc/364#s-2gw875g9 */
  val errCode: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TokenResp {
      val token = pigeonVar_list[0] as String?
      val errCode = pigeonVar_list[1] as Long?
      return TokenResp(token, errCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      token,
      errCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is TokenResp) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ResultResp (
  val success: Boolean,
  /** see https://dev.vivo.com.cn/documentCenter/doc/364#s-2gw875g9 */
  val errCode: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ResultResp {
      val success = pigeonVar_list[0] as Boolean
      val errCode = pigeonVar_list[1] as Long?
      return ResultResp(success, errCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      errCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ResultResp) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class QueryProfileIdsResp (
  val profileIds: List<String>,
  /** see https://dev.vivo.com.cn/documentCenter/doc/364#s-2gw875g9 */
  val errCode: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): QueryProfileIdsResp {
      val profileIds = pigeonVar_list[0] as List<String>
      val errCode = pigeonVar_list[1] as Long?
      return QueryProfileIdsResp(profileIds, errCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      profileIds,
      errCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is QueryProfileIdsResp) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LogLevel.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TokenResp.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ResultResp.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          QueryProfileIdsResp.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is LogLevel -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is TokenResp -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ResultResp -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is QueryProfileIdsResp -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PushInterface {
  fun setLogLevel(level: LogLevel, callback: (Result<Unit>) -> Unit)
  fun getLogLevel(callback: (Result<LogLevel>) -> Unit)
  /** 初始化push服务 */
  fun initialize(callback: (Result<Unit>) -> Unit)
  /** 打开应用push开关，订阅应用，成功后便可接收到当前应用的推送消息,  返回0表示成功，参考公共状态码 https://dev.vivo.com.cn/documentCenter/doc/364#s-2gw875g9 */
  fun openPush(callback: (Result<Long>) -> Unit)
  /** 关闭应用push开关，解订阅应用，解订阅后将收不到当前应用的推送消息,  返回0表示成功，参考公共状态码 https://dev.vivo.com.cn/documentCenter/doc/364#s-2gw875g9 */
  fun closePush(callback: (Result<Long>) -> Unit)
  /** 获取当前设备的当前应用的唯一标识，后台可基于此标识发送通知 */
  fun getRegId(callback: (Result<TokenResp>) -> Unit)
  /** 删除当前regid,  返回0表示成功，参考公共状态码 https://dev.vivo.com.cn/documentCenter/doc/364#s-2gw875g9 */
  fun deleteRegId(callback: (Result<Long>) -> Unit)
  /** 注册push，获取申请的regId */
  fun registerToken(appId: String, appKey: String, appSecret: String, callback: (Result<TokenResp>) -> Unit)
  /** 解注册push，关闭push功能 */
  fun unregisterToken(callback: (Result<ResultResp>) -> Unit)
  /** 设置标签,  返回0表示成功，参考公共状态码 https://dev.vivo.com.cn/documentCenter/doc/364#s-2gw875g9 */
  fun setTopic(topic: String, callback: (Result<Long>) -> Unit)
  /** 删除标签,  返回0表示成功，参考公共状态码 https://dev.vivo.com.cn/documentCenter/doc/364#s-2gw875g9 */
  fun deleteTopic(topic: String, callback: (Result<Long>) -> Unit)
  /** 获取当前设备的应用标签，后台可基于此标签发送通知 */
  fun getTopics(callback: (Result<List<String>>) -> Unit)
  /** 用于判断当前系统是否支持push服务 */
  fun isSupport(callback: (Result<Boolean>) -> Unit)
  /** 查询设备是否支持对应push功能 */
  fun isPushSupport(flag: Long, callback: (Result<Boolean>) -> Unit)
  /** 是否支持profileId校验功能 */
  fun isSupportSyncProfileInfo(callback: (Result<Boolean>) -> Unit)
  /** 添加应用的profileId, 添加ID只允许一次添加一个，单个profileId长度限制为64，单应用最多设置10个 */
  fun addProfileId(profileId: String, callback: (Result<ResultResp>) -> Unit)
  /** 删除应用指定的profileId */
  fun deleteProfileId(profileId: String, callback: (Result<ResultResp>) -> Unit)
  /** 除该应用下所有的profileId */
  fun deleteAllProfileId(callback: (Result<ResultResp>) -> Unit)
  /** 查询应用所有的profileId */
  fun queryProfileIds(callback: (Result<QueryProfileIdsResp>) -> Unit)
  /**
   * 查询应用的订阅状态
   * 0:已订阅状态；1：未订阅；其它：异常情况,参考公共状态码 https://dev.vivo.com.cn/documentCenter/doc/364#s-2gw875g9
   */
  fun querySubscribeState(callback: (Result<Long>) -> Unit)

  companion object {
    /** The codec used by PushInterface. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `PushInterface` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PushInterface?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vivo_push.PushInterface.setLogLevel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val levelArg = args[0] as LogLevel
            api.setLogLevel(levelArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vivo_push.PushInterface.getLogLevel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getLogLevel{ result: Result<LogLevel> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vivo_push.PushInterface.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.initialize{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vivo_push.PushInterface.openPush$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.openPush{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vivo_push.PushInterface.closePush$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.closePush{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vivo_push.PushInterface.getRegId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getRegId{ result: Result<TokenResp> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vivo_push.PushInterface.deleteRegId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.deleteRegId{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vivo_push.PushInterface.registerToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val appIdArg = args[0] as String
            val appKeyArg = args[1] as String
            val appSecretArg = args[2] as String
            api.registerToken(appIdArg, appKeyArg, appSecretArg) { result: Result<TokenResp> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vivo_push.PushInterface.unregisterToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.unregisterToken{ result: Result<ResultResp> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vivo_push.PushInterface.setTopic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val topicArg = args[0] as String
            api.setTopic(topicArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vivo_push.PushInterface.deleteTopic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val topicArg = args[0] as String
            api.deleteTopic(topicArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vivo_push.PushInterface.getTopics$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getTopics{ result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vivo_push.PushInterface.isSupport$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isSupport{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vivo_push.PushInterface.isPushSupport$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val flagArg = args[0] as Long
            api.isPushSupport(flagArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vivo_push.PushInterface.isSupportSyncProfileInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isSupportSyncProfileInfo{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vivo_push.PushInterface.addProfileId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val profileIdArg = args[0] as String
            api.addProfileId(profileIdArg) { result: Result<ResultResp> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vivo_push.PushInterface.deleteProfileId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val profileIdArg = args[0] as String
            api.deleteProfileId(profileIdArg) { result: Result<ResultResp> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vivo_push.PushInterface.deleteAllProfileId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.deleteAllProfileId{ result: Result<ResultResp> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vivo_push.PushInterface.queryProfileIds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.queryProfileIds{ result: Result<QueryProfileIdsResp> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vivo_push.PushInterface.querySubscribeState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.querySubscribeState{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
